name: Basic Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    name: Validate Plugin
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer
        coverage: none

    - name: Check PHP syntax
      run: find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \;