name: Deploy to WordPress.org
on:
  release:
    types: [released]
  # Allow manual triggering of the workflow.
  workflow_dispatch:

permissions: {}

jobs:
  release:
    name: New release to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: |
          npm install
          npm run build

      - name: Install SVN (Subversion)
        run: |
          sudo apt-get update
          sudo apt-get install subversion

      - name: Push to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2 # 2.3.0
        env:
          SLUG: polldaddy
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          BUILD_DIR: tmp/build
