name: Quality Checks

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    types: [opened, synchronize, reopened]

jobs:
  php-compatibility:
    name: PHP Compatibility (${{ matrix.php-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: Check PHP syntax
      run: find . -name "*.php" ! -path "./vendor/*" ! -path "./node_modules/*" -exec php -l {} \;

